services:
  waha:
    container_name: waha
    image: devlikeapro/waha:gows-arm
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./sessions:/app/.sessions
      - ./media:/app/.media

    networks:
      - proxy
      - backend

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  proxy:
    external: true
    name: proxy

  backend:
    external: true
    name: backend
