services:
  ocr-checker:
    build: .
    container_name: ocr-checker

    env_file:
      - .env

    volumes:
      - ./sessions:/app/sessions
      - ./results:/app/results
      - ./config:/app/config

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
