services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./n8n_data:/home/node/.n8n

    networks:
      - proxy
      - backend

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  proxy:
    external: true
    name: proxy

  backend:
    external: true
    name: backend
