services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./n8n_data:/home/node/.n8n

    networks:
      - proxy

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

networks:
  proxy:
    external: true
    name: proxy
