services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    networks:
      - proxy
      - backend

networks:
  proxy:
    external: true
    name: proxy

  backend:
    external: true
    name: backend
