services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      # Media Social Sender
      - /home/ubuntu/oshinesia/oshinesia-social-sender/media:/media/social-sender:ro

      # Media Telegram Autobackup
      - /home/ubuntu/oshinesia/oshinesia-telegram-autobackup/media:/media/telegram-autobackup:ro

    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
