services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped

    volumes:
      - ./data:/root/.ollama

    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1

    networks:
      - ollama

    cpus: "1"
    mem_limit: 2g

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  ollama:
    external: true
    name: ollama
