services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped

    ports: 
      - "11434:11434" # untuk testing

    volumes:
      - ./data:/root/.ollama

    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1

    networks:
      - ollama

    deploy:
      resources:
        limits:
          memory: 2G

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  ollama:
    external: true
    name: ollama