services:
  telegram:
    build: .
    container_name: telegram
    restart: unless-stopped

    env_file:
      - .env

    networks:
      - backend

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  backend:
    external: true
    name: backend
